### ISSUE TITLE
Add class for markers

### ISSUE THREAD

**Issue by dhcole** [cutting-room-floor/markers.js#10]
@tmcw what do you think about adding a default class to simple style markers, like the default factory does? something like `.mmg-marker`?

**Comment by tmcw** [comment]
What would be the use case?

**Comment by dhcole** [comment]
Styling the markers. Maybe altering their opacity for a highlight-on-hover effect or, as I've done on a few projects now, add an outline with another marker by using a `::before` pseudo element:

![](https://img.skitch.com/20120531-cuakeqa5sihi4w4yypx1enfybd.jpg)
