### ISSUE TITLE
Marker symbols do not print

### ISSUE THREAD

**Issue by ansis** [cutting-room-floor/markers.js#21]
http://support.mapbox.com/discussions/general-questions/2209-weekend-picks-template

From the original report:

> I've tried to use your map site template weekend-picks. There is a little problem with symbol and print.
> In simplestyle_factory.js the style class simplestyle-marker is defined with a background image (ds.backgroundImage = 'url(' + ... )
> In that way symbols are not printed.
> I think that the simplest solutions is to exchange the background images with  tags and remove ds.textIndent = '-10000px';

**Comment by tmcw** [comment]
Yeah, was just talking about this IRL. Not sure it's a priority.
