### ISSUE TITLE
Support filtering

### ISSUE THREAD

**Issue by tmcw** [cutting-room-floor/markers.js#28]
Although you can technically do this by just using `_.filter()` with the points array, it's annoying to do this since it's not repeatable.

**Comment by ansis** [comment]
Would it be a good idea to store the features that have been filtered out, so that they get added if they match a new filter?

**Comment by tmcw** [comment]
This is a cosmetic operation, it doesn't change the underlying features - see [the tests](https://github.com/mapbox/markers.js/commit/9c6396922a57d421dcca0655ef475a455f21d763#L1R175) in which new filters show previously hidden features.

**Comment by ansis** [comment]
Ah, I misread. Awesome
