### ISSUE TITLE
Clustering

### ISSUE THREAD

**Issue by lxbarth** [cutting-room-floor/markers.js#29]
@tmcw 

Often when using mmg I find myself in need for clustering. [I've repeatedly hacked my way out of it](http://infoamazonia.org/#story=post-49) Is this something that markers.js should support?

/cc @dhcole @hrwgc

**Comment by tmcw** [comment]
There's a clustering implementation with k-means in bonus/mmg_cluster.js - I know @dhcole has also implemented one that works better visually.

**Comment by lxbarth** [comment]
Ha, missed that. @dhcole - where's the one you implemented?

**Comment by dhcole** [comment]
My attempt was just hacked into MMG: https://github.com/dhcole/mmg/blob/gh-pages/src/site.js#L26-88

I would like to update this to be a plug in for markers.js, but have not had a chance to do so yet.

**Comment by tmcw** [comment]
clustr addresses this, and will continue to improve.
