### ISSUE TITLE
Multiple Marker Layers And Hover based tooltips

### ISSUE THREAD

**Issue by kinski76** [cutting-room-floor/markers.js#35]
Hi

More of a question this....

I am trying to have two marker layers on my map to display different content types. 

My first marker layer is loaded in straight away. My second is loaded when a user zooms in on a region. 

I am using css hover selectors to control the reveal of a tool tip.

What I have noticed is that when the second layer is loaded in the interaction with the first layers marker is lost. I.e the hover does not seem to work anymore. Is this expected behavior and I am approaching this incorrectly?

cheers

ade

**Comment by tmcw** [comment]
This is fixed in 0.5.3; all custom factory functions now need to set `pointer-events: all` but the default factory sets it.
