### ISSUE TITLE
Tooltip stacking bug

### ISSUE THREAD

**Issue by tmcw** [cutting-room-floor/markers.js#48]
This has come up in support a few times
- http://support.mapbox.com/discussions/mapbox-tiles/532-force-tooltips-to-be-above-all-the-layers

We need to make sure that tooltips are always above all marker layers.

**Comment by arosboro** [comment]
I am interested in seeing this fixed too.

**Comment by fdl042** [comment]
Any update on this ? This bug happened to me, too.
